### ISSUE TITLE
spine: text orientation attribute

### ISSUE THREAD

**Issue by xaratustrah** [aerkalov/ebooklib#109]
Hi and thanks, ebooklib works like a charm. My questions: is there a way to change `spine` and `body` attributes to support text orientation from right to left needed for RTL languages? Currently the following has to be modified _manually_ after creation of the epub, inside the zip file. In **EPUB/content.opf**:

`<spine toc=“mcx” page-progression-direction="rtl">`

and in main content / chapter

`<body dir=“rtl”>`

**Comment by aerkalov** [comment]
Hi!

It is not possible at the moment. I did use it to produce some books RTL languages in the past but clearly better support is needed. Will take a look at the specification and see what is missing.

**Comment by aerkalov** [comment]
I pushed the changes to https://github.com/aerkalov/ebooklib/tree/rtl branch. Will merge it later when I double check the issues and maybe fix the docs for it. 

You can do book.set_direction('rtl') and on the HtmlItems you can define item.direction to use whatever is needed.
