### ISSUE TITLE
Documentation not generated

### ISSUE THREAD

**Issue by henningvs** [aerkalov/ebooklib#118]
When reading http://ebooklib.readthedocs.io/en/latest/ it seems that there is no docuemtation for the main modules generated. Is this correct?

![image](https://cloud.githubusercontent.com/assets/5406293/23832289/1f485c92-0732-11e7-9924-3a1a2e98062b.png)

**Comment by aerkalov** [comment]
Correct. I had to get access to readthedocs site to check this out. I would say it works now. I had to turn on option to install library from the setup.py to make it work.

if you check links now (http://ebooklib.readthedocs.io/en/latest/ebooklib.html#id1) it should show autogenerated docs.

**Comment by henningvs** [comment]
I can confirm; the documentation is now generated and visible.
Thank you for the quick fix!
