### ISSUE TITLE
Lost all images except epub cover

### ISSUE THREAD

**Issue by Cologler** [aerkalov/ebooklib#120]
env: python 3.6 + windows 10 x64.

``` py
from ebooklib import epub

e = epub.read_epub(source)
epub.write_epub(dest, e)
```

then:

![picpick-20170511-155249-001](https://cloud.githubusercontent.com/assets/10906962/25938523/1522fa10-3662-11e7-9f0c-1ce9aff46a17.png)

**Comment by aerkalov** [comment]
Just doing _read_epub_ and _write_epub_ after that would not do the trick. For instance path to the images is different, some issues with metadata and etc. So the idea is that you read content and then generate new EPUB file from scratch. Reformat HTML content to include new path, change the file names if they are not valid and etc. 

But thinking about it now I would say the time has come to fix this issue also. If you don't have problems you with the content you can send me the EPUB to check what is going on and see how to make pure read+write work. My email is aerkalov@gmail.com.

Aco

**Comment by aerkalov** [comment]
Just closing this issue. Will write new ticket for the proper read+write solution.
