### ISSUE TITLE
Cover and title do not appear on the homepage

### ISSUE THREAD

**Issue by patriciaramos1995** [aerkalov/ebooklib#127]
Good afternoon,
I've added the cover and epub title, but only the cover is displayed on the homepage. If the title is set, should not it appear overlapping the cover image?

I followed this example to develop: https://github.com/aerkalov/ebooklib/blob/master/samples/02_cover_create/create.py

**Comment by aerkalov** [comment]
Hi!

What application are you using to read the created epub file? When it comes to cover page ebook readers will show just cover image without the title (when reading the book; might be different when browsing the books). But what homepage are you talking about? 

Aco

**Comment by patriciaramos1995** [comment]
The application I use is iBooks. The homepage I said is the cover of the book. In iBooks, the book cover is displayed in the available book listing, note the image below, there are books with the title and author, and there are books with only the picture. Is it possible to put both the image and the title on the cover?



![image](https://user-images.githubusercontent.com/20867368/28462328-2546380a-6df1-11e7-9b00-fcea122df16e.png)

**Comment by aerkalov** [comment]
iBooks will show book title and author's name when cover image is not defined. When epub has defined cover it will only show to cover image. So if you want to have title of the book or author's name you would have to edit the cover image and put it there.
