### ISSUE TITLE
duplicate id:identifier in generated epub

### ISSUE THREAD

**Issue by xzcvczx** [aerkalov/ebooklib#128]
```
    <meta content="Ebook-lib 0.15.0" name="generator" />
    <dc:identifier id="id">1234567890</dc:identifier>
    <meta content="cover-img" name="cover" />
    <dc:identifier id="id">1234567890</dc:identifier>
```

when i generate the epub and open it in sigil i find that the identifier field is repeated. Is this expected/intended behaviour?

**Comment by aerkalov** [comment]
Can you show the sample code? It should not happen and i can not reproduce it with my test code.

**Comment by xzcvczx** [comment]
yeah sorry about that it seems to have fixed itself now and i have no idea what i changed
