### ISSUE TITLE
Wrong rules in MANIFEST.in

### ISSUE THREAD

**Issue by tantale** [aerkalov/ebooklib#139]
The rules in `MANIFEST.in` are incomplete and wrong.

You should have:

```
include *.txt
recursive-include docs *.py
recursive-include docs *.rst
recursive-include docs Makefile
recursive-include samples *.jpg
recursive-include samples *.md
recursive-include samples *.py
```

But you also need to:

- rename `CHANGES.TXT` to `CHANGES.txt`,
- rename `docs/_static/README` to `docs/_static/README.rst`,
- delete `MANIFEST`.

To check your manifest file, activate your `virtualenv` and run:

    check-manifest

**Comment by aerkalov** [comment]
Will merge this with small change.

check-manifest does return different results depending if you run it with python2 or python3. For python3 it asks for:
`include *.md`

Also, README should not be renamed to README.rst. Sphinx will throw warning message in that case and it is not part of the documentation anyway but rather dummy file just to hold the directory.

`checking consistency... .../_static/README.rst: WARNING: document isn't included in any toctree`
