### ISSUE TITLE
It can't be work with multiple plugins?

### ISSUE THREAD

**Issue by choryuidentify** [aerkalov/ebooklib#145]
Hi!

I've some testing to this library on windows, but [standard tidy plugin](https://github.com/aerkalov/ebooklib/blob/master/ebooklib/plugins/tidyhtml.py) is not work on windows.

cause I've make [tidy plugin using BeautifulSoup4](https://gist.github.com/choryuidentify/1b7b24a07082ca9e9e9b6e2ac027a50b), and [write test code.](https://gist.github.com/choryuidentify/41b32be2ca9bf0f42c8822c35d5ac86b)

But it does not works. processed xhtml file is empty.
![2018-02-08 10_31_05-new issue aerkalov_ebooklib](https://user-images.githubusercontent.com/14815572/35950725-3cb75618-0cbb-11e8-8750-1b10a9dc9dc8.png)

It just works using single plugin 'standard.SyntaxPlugin()' or 'bstidy.TidyPlugin()', but dosen't work with both.
It's a bug? or my mistake?

Thank you.

**Comment by aerkalov** [comment]
Hi!

I would say it is something with your setup. I just tried that code on OSX and it produced non empty intro.xhtml file. In general I have not seen errors with multiple plugins. Will try to find Windows machine to try it there.

Aco

**Comment by choryuidentify** [comment]
I've test this on another PC, It generate non-empty intro.xhtml but tidy is not applied.
Add 'print' function for debug, It printing tidy-applied strings but saved intro.xhtml is different to printed strings.
![2018-02-11 15_09_59-syosetu-grabber d__pycharmprojects_syosetu-grabber - _manager_filemanager-e](https://user-images.githubusercontent.com/14815572/36070427-b1ba5df0-0f3d-11e8-8c0a-eeb6adaec698.png)
