### ISSUE TITLE
How can I use this to find if pages are missing from the book?

### ISSUE THREAD

**Issue by hussaintamboli** [aerkalov/ebooklib#157]

**Comment by aerkalov** [comment]
Can you explain this more? Pages which are inside of the EPUB file but are not listed in Table of Contents or you were thinking about something else?

**Comment by hussaintamboli** [comment]
This has happened to me few times, I started reading an ebook and halfway thorough I found few pages missing. e.g. p128, p129, p156, p157, ..

I want to be able to find p129 to p156 are missing.

**Comment by aerkalov** [comment]
What ebook reader or application you are using to read? I assume this might be connected more with  app/reader than the library. I have no idea how is book created or organised but you can check if it has defined page-list (http://epubsecrets.com/page-list-all-the-cool-ebook-developers-are-doing-it.php). Maybe that is wrongly defined and ebook reader shows wrong info.
