### ISSUE TITLE
How do I read an epub book from file object?

### ISSUE THREAD

**Issue by LoganDark** [aerkalov/ebooklib#158]
On Google App Engine, I'm going to store epub books on Google Cloud Storage, so how do I read them when I can't write the file to the file system?

**Comment by aerkalov** [comment]
There is no straightforward way how to do it. You need to pass path to the epub file. But this does look like it could be useful feature.

**Comment by What-If-I** [comment]
@LoganDark 
I had the similar problem and thought my approach can help you or anyone else with this issue. The way it can be handled is to wrap file content in BytesIO.

```
from io import BytesIO
from ebooklib import epub

content = b"binary string"
book = epub.read_epub(BytesIO(content))
```

**Comment by jamesleeht** [comment]
> @LoganDark I had similar problem and thought my approach can help you or anyone else with this issue. The way it can be handled is to wrap file content in BytesIO.
> 
> ```
> from io import BytesIO
> from ebooklib import epub
> 
> content = b"binary string"
> book = epub.read_epub(BytesIO(content))
> ```

Thanks for sharing - it seems like this does not work on the newest version of the library.

```
stat: path should be string, bytes, os.PathLike or integer, not BytesIO
```

Is this intended or a regression? cc @aerkalov
