### ISSUE TITLE
Load images inside html

### ISSUE THREAD

**Issue by Kogam22** [aerkalov/ebooklib#169]
Hello there!
Suppose I have a HTML Page with images. 
I get that page, process with bs4 to check for images. If images are found, I download them. 
Problem Is, how to add them inside the epub's xhtml page in the same place they were in the earlier HTML page ? Are there any native methods for this ? If yes, how to use them ?

**My thoughts:** 

- If I have to change the `src`, then where to point at ? Because if epub is moved from original place, any external `src` location will be invalid.

- Do i have to use `book.add_item()` method ? Can you explain how to use it ?

Thanks.

**Comment by aerkalov** [comment]
Exactly like that. For any reference to an image you need to download that file and rewrite the src. You also need to be careful when linking to other page inside of that site. For instance, you might have link "../mypage/something" which you would need to rewrite into "../mypage/something.xhtml" or even better to "something.xhtml". Most likely you would not need to have the same file structure as on the website, maybe you would like to have all files in the same directory. It is up to you but you need to rewrite these things for sure. The biggest issue is if you want to use their CSS which has link references. Then you might not be able to use your new layout for the structure of files (or you could rewrite CSS).

If we imagine page with URL http://www.mysite.com/about/us.html and code inside with `<img src="/images/logo.png">` we would most likely like to have just page us.xhtml and code inside `<img src="Images/logo.png">`. 

And if you had link `<a href="/">Index</a>` you would need to rewrite it with `<a href="home.xhtml">index</a>`.

At the end the structure of EPUB would be:

```
/mimetype
/META-INF/
                  /container.xml
/EPUB/
           /images/
                         /logo.png
          /us.xhtml
          /home.xhtml

```

**Comment by Kogam22** [comment]
Thanks for the reply!

@aerkalov :
> If we imagine page with URL http://www.mysite.com/about/us.html and code inside with `<img src="/images/logo.png">` we would most likely like to have just page `us.xhtml` and code inside `<img src="Images/logo.png">`.

As the EPUB structure is 

> ```
> /mimetype
> /META-INF/
>                   /container.xml
> /EPUB/
>            /images/
>                          /logo.png
>           /us.xhtml
>           /home.xhtml
> ```


then I think there is a typo in the `src="Images/logo.png"` which should be `src="images/logo.png"`, right ?


--------------------------------------------------------------------------------------

Check this . . . Is it proper ?

```
def download_img(tag):
    for img in tag.select('img'):
        src = img.get('src')
        r = req.get(src)
        img_name = src.split('/')[-1]
        with open(img_name, 'wb') as f:  
                f.write(r.content)
        image = open(img_name, 'rb').read()
        img_file = epub.EpubItem(file_name=img_name,
                        media_type="image",     # I don't exactly know if image type will be png/jpg/jpeg etc
                        content=image)
        book.add_item(img_file)
        img['src'] = "images/" + img_name #Change src
```

**Comment by aerkalov** [comment]
Sure, it should be "images" or "Images" in both places.

Your file_name must be 'images/' + img_name. You need to specify directory name in the path also.

You don't need to use media_type. It is really "Content Type" and it will guess it from you file extension (like image/png, image/jpeg, ...). So just ignore it. In theory you should be careful and not end up with two images with the same name. So to be 100% correct you would also need to see if img_name already exists in the images directory and change it into img_name  + something random for instance.

**Comment by Kogam22** [comment]
@aerkalov :
>So to be 100% correct you would also need to see if img_name already exists in the images directory and change it into img_name + something random for instance.

Well, how do I check for a particular file inside of an EPUB which is being created ? Like the normal `os.exists()` ?

**Comment by aerkalov** [comment]
You can do something like this to check if file with that path exists inside:

```
index = book.get_item_with_href('index.xhtml')
```
