### ISSUE TITLE
add c.content error

### ISSUE THREAD

**Issue by WangTingZheng** [aerkalov/ebooklib#190]
when I add a str value to c.content, I having a error:
```
lxml.etree.ParserError: Document is empty
```
code:
```python
temp = "<html><head>" + title + "</head>" + "<body>" + text + "</body></html>"
c.content = temp
```

`tile` and `text` are all str value
when I changed the code like this:

```
temp = "<html><head>" + title + "</head>" + "<body>" + text + "</body></html>"
c.content = "|"+temp+"|"
```
It's ok. Why?

**Comment by aerkalov** [comment]
Did you figure out where was the problem? It does look like an interesting problem.

**Comment by WangTingZheng** [comment]
> 
> 
> Did you figure out where was the problem? It does look like an interesting problem.

yes, This variable should be a string in HTML format. My temp variable has a grammatical error in html. But I still don't figure out that why I add "|" to temp can't fix this bug.

**Comment by WangTingZheng** [comment]
> 
> 
> Did you figure out where was the problem? It does look like an interesting problem.

This is my [code](https://github.com/WangTingZheng/PureWriterBackup/blob/ffb97ad360ca5d01017e9e9dc12e7c10e79332c5/app/epub.py#L67)

**Comment by BrianZbr** [comment]
@aerkalov I'm getting this same `Document is empty` error from lxml when I run [your basic creation sample](https://github.com/aerkalov/ebooklib/blob/master/samples/01_basic_create/create.py). I see that hasn't been updated in a very long time. I'm wondering if this problem has to do with updates to lxml, or something else. Any advice?

**Comment by Jemeni11** [comment]
Hey @aerkalov I'm also getting a `Document is empty` error. Here's [a gist](https://gist.github.com/Jemeni11/b297e899244bf974c03df06499cfd2d4) with my code.
I also uploaded the epub here although I had to change the file extension to zip just to upload it.
[[copy]Endo_Worm_AU_Kid_Win_by_nokko-b9dnsl9t.zip](https://github.com/aerkalov/ebooklib/files/11374820/copy.Endo_Worm_AU_Kid_Win_by_nokko-b9dnsl9t.zip)

**Comment by Jemeni11** [comment]
> Hey @aerkalov I'm also getting a `Document is empty` error. Here's [a gist](https://gist.github.com/Jemeni11/b297e899244bf974c03df06499cfd2d4) with my code. I also uploaded the epub here although I had to change the file extension to zip just to upload it. [[copy]Endo_Worm_AU_Kid_Win_by_nokko-b9dnsl9t.zip](https://github.com/aerkalov/ebooklib/files/11374820/copy.Endo_Worm_AU_Kid_Win_by_nokko-b9dnsl9t.zip)

With help, I've fixed it!
There were a bunch of minor errors but the major one was this:
```py
item.content = str(soup)
```
It should have been:
```py
item.content = str(soup).encode('utf-8')
```
