### ISSUE TITLE
using ebook.guide?

### ISSUE THREAD

**Issue by charely6** [aerkalov/ebooklib#191]
There is no documentation about what needs to be put into ebook.guide?
I am attempting to create an ebook to be loaded on a nook classic but it just keeps not working. I am not sure why but I suspect its because I am missing the guide entries but I don't really know that for sure. I would like to try adding it to test that but I don't know how ebooklib uses it.

**Comment by aerkalov** [comment]
True, we might add it to the docs. It is just a list of dictionaries. Here is an example:

```
                    epub_book.guide.append({
                        'type': 'text',
                        'href': chapter_href,
                        'title': chapter_title,
                    })
```
