### ISSUE TITLE
EPUB2 error while exporting

### ISSUE THREAD

**Issue by csantanu** [aerkalov/ebooklib#196]
Hi,

I am getting this error while using the Booktype installation which uses ebooklib as core package. Strangely, this is not happening with EPUB3 format and it is perfectly exporting.

When I am publishing using EPUB2 format, I am getting this error : KeyError : 'package_direction'.

  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 375, $
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 632, $
    return self.run(*args, **kwargs)
  File "/usr/local/src/booktype/lib/booktype/apps/convert/tasks.py", line 50, i$
    return func(request, *args, **kwargs)
  File "/usr/local/src/booktype/lib/booktype/apps/convert/tasks.py", line 66, i$
    result = run_conversion(*args, **kwargs)
  File "/usr/local/src/booktype/lib/booktype/convert/runner.py", line 58, in ru$
    conversion_result = converter.convert(book, output)
  File "/usr/local/src/booktype/lib/booktype/convert/epub/converter.py", line 1$
    epub_writer.write()
  File "/usr/local/lib/python2.7/dist-packages/ebooklib/epub.py", line 1223, in$
    self._write_opf_file()
  File "/usr/local/lib/python2.7/dist-packages/ebooklib/epub.py", line 858, in $
    if self.book.direction and self.options['package_direction']:
KeyError: 'package_direction'

Please help!
Thanks.
Santanu

**Comment by laudrain** [comment]
trying an advice: stop producing EPUB2 ;)
All what EPUB2 does is done better with EPUB3...

**Comment by csantanu** [comment]
Yes, I can take the EPUB3 route. But it produces a 'Guide' by default that is typically not required for most of the titles. How to switch off this feature? Booktype does not provide any interface for setting this up for EPUB3 format.

**Comment by aerkalov** [comment]
I haven't been working on the Booktype for couple of years so I wouldn't really know what have they changed but if you have your own installation you can always modify default options in file:  /lib/booktype/convert/epub/writer.py

```
class Epub3Writer(ebooklib.epub.EpubWriter):
    DEFAULT_OPTIONS = {
        'epub2_guide': True,
        'epub3_landmark': True,
        'epub3_pages': True,
        'landmark_title': 'Guide',
        'pages_title': 'Pages',
        'spine_direction': True,
        'package_direction': False,
        'play_order': {
            'enabled': False,
            'start_from': 1
        }
    }
```

I just copy + pasted default options from ebooklib but modify it as you like. That will produce EPUB3 without guide.

**Comment by laudrain** [comment]
@csantanu I don't know Booktype. Thanks @aerkalov.
 
On guide element, latest EPUB 3.2 spec says:
> `The guide element [OPF2] is a legacy feature that previously provided machine-processable navigation to key structures in an EPUB Publication. It is replaced in EPUB 3 by landmarks in the EPUB Navigation Document.`

**Comment by csantanu** [comment]
Thanks @aerkalov 
I have solved the above mentioned bug as well. In the booktype writer implementation under the epub2 writer class this default option was set - 
DEFAULT_OPTIONS = {
        'epub2_guide': True,
        'epub3_landmark': False,
        'landmark_title': 'Guide'
    }
This was throwing the error for package_direction key which was coming as null. After putting the entire default options chunk here, now epub2 export is working fine.
