### ISSUE TITLE
Use of .txt files as opposed to .xhtml files

### ISSUE THREAD

**Issue by Nucl3arSn3k** [aerkalov/ebooklib#210]
In the example shown in the documentation for this library 

`c1 = epub.EpubHtml(title='Introduction',
                   file_name='intro.xhtml',
                   lang='en')`

Would it be possible to call another class function to use a .txt file to make the content for the .epub file,as opposed to using a .xhtml file?

**Comment by aerkalov** [comment]
You can just do ```epub.EpubHtml(title='Introduction', file_name='intro.txt', lang='en')``` and it should work. Reading would also probably work, you would just end up with ```EpubItem``` object instead of ```EpubHtml```.
