### ISSUE TITLE
Very confused

### ISSUE THREAD

**Issue by caarson** [aerkalov/ebooklib#220]
Hello, I am very confused regarding why my book is not properly exporting.

I have little experience with eBookLib and I couldn't figure it out:
`        # set project directory:
        ROOT_DIR = os.path.dirname(os.path.abspath(__file__))

        #####
        # convert the url to an image file and save it in ClientAlphaNeo/bookcovers:

        # declare directories:
        full_file_name_for_cover = os.path.join(ROOT_DIR + "\\bookcovers", book_name + ".jpg")

        # send http request and get the image and save it:
        urllib.request.urlretrieve(book_cover, full_file_name_for_cover)

        #####
        # set meta-data:

        # create book directory for saving books:
        full_file_name_for_novel = os.path.join(ROOT_DIR + "\\books")

        # set the meta-data:
        book.set_title(str(book_name))
        book.set_identifier("NA12345")
        book.set_language(str(language_for_book))
        book.add_author(str(book_author))
        book.set_cover(full_file_name_for_cover, open(full_file_name_for_cover, 'rb').read())

        # add default NCX and Nav file
        book.add_item(epub.EpubNcx())
        book.add_item(epub.EpubNav())

        # define CSS style
        style = 'BODY {color: white;}'
        nav_css = epub.EpubItem(uid="style_nav", file_name="style/nav.css", media_type="text/css", content=style)

        # add CSS file
        book.add_item(nav_css)

        # list of chapters
        chapter = []

        # denotes end of setting up book

        ######
        # begin exporting xml and finalizing books:
        ######

        # declare a place to save scrape data:
        chapters_local = scrape_data

        # Initialize variables for the loop:
        number = 0

        # cycle through chapters:
        for chapter in chapters_local:
            # increment by 1
            number = number + 1

            # create name for the file for temp storage of chapter data;
            chapter_name = "chapter" + str(number)

            # open a file for the temp storage of an XML file:
            xml_file = open(chapter_name, 'w')

            # create book directory for saving books:
            full_file_name_for_novel = os.path.join(ROOT_DIR + "\\books")

            ''' outdated code 
            # write and close the file:
            xml_file.write(os.path.join(ROOT_DIR + "\\temp"))
            xml_file.close()
            '''

            ####
            # Chapter Content:

            # create chapter objects:
            chapter_content = epub.EpubHtml(title=book_name,
                               file_name=book_name + str(number) +'.xhtml',
                               lang='en')
            # load in & set content - an attribute of chapter
            chapter_content.set_content('<html><body><p>' + chapter + '</p></body></html>')

            # add content to book:
            book.add_item(chapter_content)

            # add chapter to spine
            chapters_local.append(chapter_name)

        spine = ['nav']
        for chapter in chapters_local:
            spine.append(chapter)

        # define Table Of Contents
        book.toc = (epub.Link('chap_01.xhtml', 'Introduction', 'intro'), (epub.Section('Simple book'), chapters_local))

        # define the basic spine
        book.spine = spine

        # write file:
        epub.write_epub(full_file_name_for_novel + "\\" + book_name + '.epub', book)
        print("Output at: \n" + full_file_name_for_novel + "\\" + book_name + '.epub')
`
I don't if the .xhtml is supposed to made or not, what I want to do is be able to set the value of each chapter. 
This line I think does that but I'm not sure:            
 # create chapter objects:
            chapter_content = epub.EpubHtml(title=book_name,
                               file_name=book_name + str(number) +'.xhtml',
                               lang='en')
            # load in & set content - an attribute of chapter
            chapter_content.set_content('<html><body><p>' + chapter + '</p></body></html>')

**If I could get your discord, or maybe if there's a discord for ebooklib that would be super helpful.**

Thank you for your time and I'm grateful for any assistance,
Carson.

**Comment by Pioverpie** [comment]
I'm not the author, but I use ebooklib frequently and am willing to help. While I can't find any sort of Discord server for this package, if you send a friend request to Pioverpie#6539 on Discord I'd be happy to go over your code with you.

**Comment by caarson** [comment]
> I'm not the author, but I use ebooklib frequently and am willing to help. While I can't find any sort of Discord server for this package, if you send a friend request to Pioverpie#6539 on Discord I'd be happy to go over your code with you.

Thank you for your kind offer, I have added you.

**Comment by caarson** [comment]
Still waiting on a solution! @Pioverpie would you be kind enough to add me back? I would be very grateful!

**Comment by aerkalov** [comment]
Hi!

I tested it and fixed couple of things. I validated the output file with epubcheck and it seems to work.

I assumed that you only provide content of the chapter inside of scrape_data variable. It would be a bit different
if you already have title of the chapter from somewhere and etc. I have put some comments inside. Hope this would help.

You had couple of errors with path to the cover image and what you were appending to chapters_local. At least for me this all ended in dead loop. You also added some non existing chapters (basically that Link and Section thing) which would fail validation.

Hope it helps and please ask for more if you need some explanation.

Aco

```
    full_file_name_for_cover = os.path.join(ROOT_DIR,  "bookcovers", book_name + ".jpg")
    # send http request and get the image and save it:
    urllib.request.urlretrieve(book_cover, full_file_name_for_cover)

    book = epub.EpubBook()

    book.set_title(str(book_name))
    book.set_identifier("NA12345")
    book.set_language(str(language_for_book))
    book.add_author(str(book_author))

    # This ASSUMES cover is PNG. Extension must be correct because content type will be guessed
    # according to the extension.

    # This will put file at EPUB/cover.png location. If you used 'images/cover.png' it would be
    # placed in EPUB/images/cover.png location. The 2nd thing is what you want. You want
    # to put all images in images/ .css files in style/ and etc.

    # This first argument is location inside of EPUB file, not where it is on the disk.

    book.set_cover('cover.png', open(full_file_name_for_cover, 'rb').read())

    # add default NCX and Nav file
    book.add_item(epub.EpubNcx())
    book.add_item(epub.EpubNav())

    # define CSS style
    style = 'BODY {color: white;}'
    nav_css = epub.EpubItem(uid="style_nav", file_name="style/nav.css", media_type="text/css", content=style)

    # add CSS file
    book.add_item(nav_css)

    # I ASSUME here that scrape_data is something like ['content of chapter 1', 'content of chapter 2']
    chapters_local = scrape_data

    # Initialize variables for the loop:
    number = 0

    # cycle through chapters:
    spine = ['nav']
    toc = []

    for content in chapters_local:
        number = number + 1

        # create chapter objects:
        chapter = epub.EpubHtml(
                           title=book_name,
                           file_name='chapter' + str(number) +'.xhtml',
                           lang='en')

        chapter.set_content('<html><body><p>' + content + '</p></body></html>')

        book.add_item(chapter)

        spine.append(chapter)
        toc.append(chapter)


    # Everything you put in spine and toc must exists inside of the book. EPUB will bot be valid if
    # they don't exist.

    book.spine = spine

    # This is very simple version of the TOC. It puts all of your chapters inside of one Section.
    book.toc = ((epub.Section('My book'), toc), )

    # This is without any sections
    # book.toc = toc

    # write file:
    epub.write_epub(os.path.join(ROOT_DIR, "books", book_name + '.epub'), book)

```

**Comment by aerkalov** [comment]
Also, I don't know how much you are familiar with EPUB files. It is just .ZIP file really so just rename it to .zip and unpack it to see what is the structure on the disk. This will help you as your chapters might have at some point images and styling files. So just to get familiar with directory structure inside of file and how to format your url paths inside of chapter to import them.

**Comment by caarson** [comment]
> Hi!
> 
> I tested it and fixed couple of things. I validated the output file with epubcheck and it seems to work.
> 
> I assumed that you only provide content of the chapter inside of scrape_data variable. It would be a bit different
> if you already have title of the chapter from somewhere and etc. I have put some comments inside. Hope this would help.
> 
> You had couple of errors with path to the cover image and what you were appending to chapters_local. At least for me this all ended in dead loop. You also added some non existing chapters (basically that Link and Section thing) which would fail validation.
> 
> Hope it helps and please ask for more if you need some explanation.
> 
> Aco
> 
> ```
>     full_file_name_for_cover = os.path.join(ROOT_DIR,  "bookcovers", book_name + ".jpg")
>     # send http request and get the image and save it:
>     urllib.request.urlretrieve(book_cover, full_file_name_for_cover)
> 
>     book = epub.EpubBook()
> 
>     book.set_title(str(book_name))
>     book.set_identifier("NA12345")
>     book.set_language(str(language_for_book))
>     book.add_author(str(book_author))
> 
>     # This ASSUMES cover is PNG. Extension must be correct because content type will be guessed
>     # according to the extension.
> 
>     # This will put file at EPUB/cover.png location. If you used 'images/cover.png' it would be
>     # placed in EPUB/images/cover.png location. The 2nd thing is what you want. You want
>     # to put all images in images/ .css files in style/ and etc.
> 
>     # This first argument is location inside of EPUB file, not where it is on the disk.
> 
>     book.set_cover('cover.png', open(full_file_name_for_cover, 'rb').read())
> 
>     # add default NCX and Nav file
>     book.add_item(epub.EpubNcx())
>     book.add_item(epub.EpubNav())
> 
>     # define CSS style
>     style = 'BODY {color: white;}'
>     nav_css = epub.EpubItem(uid="style_nav", file_name="style/nav.css", media_type="text/css", content=style)
> 
>     # add CSS file
>     book.add_item(nav_css)
> 
>     # I ASSUME here that scrape_data is something like ['content of chapter 1', 'content of chapter 2']
>     chapters_local = scrape_data
> 
>     # Initialize variables for the loop:
>     number = 0
> 
>     # cycle through chapters:
>     spine = ['nav']
>     toc = []
> 
>     for content in chapters_local:
>         number = number + 1
> 
>         # create chapter objects:
>         chapter = epub.EpubHtml(
>                            title=book_name,
>                            file_name='chapter' + str(number) +'.xhtml',
>                            lang='en')
> 
>         chapter.set_content('<html><body><p>' + content + '</p></body></html>')
> 
>         book.add_item(chapter)
> 
>         spine.append(chapter)
>         toc.append(chapter)
> 
> 
>     # Everything you put in spine and toc must exists inside of the book. EPUB will bot be valid if
>     # they don't exist.
> 
>     book.spine = spine
> 
>     # This is very simple version of the TOC. It puts all of your chapters inside of one Section.
>     book.toc = ((epub.Section('My book'), toc), )
> 
>     # This is without any sections
>     # book.toc = toc
> 
>     # write file:
>     epub.write_epub(os.path.join(ROOT_DIR, "books", book_name + '.epub'), book)
> ```

Hey thank you so much Aleksandar this is wonderful and I am very grateful to have you help me figure out eBookLib.

I don't have much experience with epub files, so I was really grateful when you explain to me some of the basic stuff about epub, maybe we can add this to the documentation!

So my question now is regarding the cover, I don't seem to have the cover showing up on my own, here's my code for the cover, is it something that I'm doing wrong?
` 
 #####
        # convert the url to an image file and save it in ClientAlphaNeo/bookcovers:
        full_file_name_for_cover = os.path.join(ROOT_DIR, "bookcovers", book_name + ".png")

        # send http request and get the image and save it:
        urllib.request.urlretrieve(book_cover, full_file_name_for_cover)

        book = epub.EpubBook()

        book.set_title(str(book_name))
        book.set_identifier("NA12345")
        book.set_language(str(language_for_book))
        book.add_author(str(book_author))

        # This ASSUMES cover is PNG. Extension must be correct because content type will be guessed
        # according to the extension.

        # This will put file at EPUB/cover.png location. If you used 'images/cover.png' it would be
        # placed in EPUB/images/cover.png location. The 2nd thing is what you want. You want
        # to put all images in images/ .css files in style/ and etc.

        # This first argument is location inside of EPUB file, not where it is on the disk.
        book.set_cover(book_name + '.png', open(full_file_name_for_cover, 'rb').read())
`
I'm under the assumption that this is all the code I should need to give, if you need the rest please let me know and I can send more.

As you can see I actually have my book covers saved in a directory, I want to grab it from there and use it in the book, I think this line accomplishes the aforementioned:

**Comment by aerkalov** [comment]
Ok, so ``set_cover()`` really defines something like a thumbnail for the book and not really the cover image you will see when you read the book. This cover image will be seen if you import your EPUB book into Calibre or iBooks for instance. To make the real cover you need to create cover page. 

Same thing as any of the chapters in the book and you have to add it to the TOC and spine (if you want). So for instance for the upper code you need to create Chapter for instance called chapter.xhtml with content ``<html><body><img src="cover.png"/></body></html>``. This is extremely simple version of the cover page because you need to define also CSS for the image to be stretched in full screen. This depends very much of the device or reader and I have no idea how much has that changed last 2-3 years.

I don't have that part in my head at the moment but you are right, maybe that should be in the documentation :)

Aco

**Comment by caarson** [comment]
> Ok, so `set_cover()` really defines something like a thumbnail for the book and not really the cover image you will see when you read the book. This cover image will be seen if you import your EPUB book into Calibre or iBooks, for instance. To make the real cover, you need to create a cover page.
> 
> Same thing as any of the chapters in the book, and you have to add it to the TOC and spine (if you want). So for instance for the upper code you need to create Chapter for instance called chapter.XHTML with content `<html><body><img src="cover.png"/></body></html>`. This is an extremely simple version of the cover page because you need to define CSS for the image to be stretched in full screen. This depends very much of the device or reader and I have no idea how much has that changed last 2-3 years.
> 
> I don't have that part in my head at the moment but you are right, maybe that should be in the documentation :)
> 
> Aco

This is absolutely excellent information. I wouldn't know much about the epub either! Perhaps these comments should be included in the documentation so other people can research the advanced functionality of epub themselves. It may just be a good idea that we include a base understanding of epub.

Once again, thank you for your help, and it was tremendously helpful as well as a good learning experience,
Carson.
