### ISSUE TITLE
EpubImage lacks parameters

### ISSUE THREAD

**Issue by bronger** [aerkalov/ebooklib#231]
In `EpubImage`, the constructor lacks parameters. For example, in https://github.com/aerkalov/ebooklib/issues/194#issuecomment-547263657, the comment author had to set the attributes afterwards manually. This thwarts encapsulation. Possibly, it is okay to use `**kwargs` for `EpubImage.__init__`, but possibly it must be more fine-grained.

**Comment by aerkalov** [comment]
Fixed! Thanks for this.
