### ISSUE TITLE
Kindlegen

### ISSUE THREAD

**Issue by angelsdemos** [aerkalov/ebooklib#238]
Kindlegen is not supported anymore. What about mobi support ?

**Comment by advancejar** [comment]
Try calibre

**Comment by aerkalov** [comment]
Yeah, ebook-convert tool from Calibre would be your best option. Very early on we had minimalistic mobi support but we ended ditching it and sticking only to EPUB.

**Comment by c1924959470** [comment]
您好！您的来信我已接受，我会尽快回复您。
