### ISSUE TITLE
Maybe elif is more appropriate

### ISSUE THREAD

**Issue by booknc** [aerkalov/ebooklib#250]
https://github.com/aerkalov/ebooklib/blob/2d48a746852d5a791acdf3de793e617c0349c826/ebooklib/epub.py#L1502
Maybe elif is more appropriate
            if media_type == 'application/x-dtbncx+xml':
                ei = EpubNcx(uid=r.get('id'), file_name=unquote(r.get('href')))

                ei.content = self.read_file(zip_path.join(self.opf_dir, ei.file_name))
            if media_type == 'application/smil+xml':                                                           <------------------------------- this line
                ei = EpubSMIL(uid=r.get('id'), file_name=unquote(r.get('href')))

                ei.content = self.read_file(zip_path.join(self.opf_dir, ei.file_name))
            elif media_type == 'application/xhtml+xml':

Otherwise, EpubNcx is eventually replaced with EpubItem

**Comment by aerkalov** [comment]
Thanks! Yes, for sure :) Just merged PR someone send about this!
