### ISSUE TITLE
PLEASE update the package on Pypi

### ISSUE THREAD

**Issue by avalonv** [aerkalov/ebooklib#268]
I'm developing a comic converter which depends on this library, but I cannot list it as a dependency due to the version available on Pypi being outdated and incompatible with my code. Could you please update it? It's been three years since the last release, and there are lots of issues complaining about errors caused by the documentation not matching what's on PyPi.

**Comment by avalonv** [comment]
I created a fork on [PyPi](https://pypi.org/project/EbookLib-re/) in the meantime, but I would appreciate being able to use the original in the long term.

**Comment by aerkalov** [comment]
Good point. Will release new version this week.

**Comment by avalonv** [comment]
Thank you. Sorry for the caps btw, I was slightly desperate
