### ISSUE TITLE
Unicode error when reading setup.py

### ISSUE THREAD

**Issue by hnykda** [aerkalov/ebooklib#75]
Hello,

I was getting error on ARM platform when trying to install ebooklib from pypi. Line 13 in `setup.py`, `long_description` should be with encoding specified. With this it works fine:
```
long_description = open('README.md', encoding="utf8").read()
```

Thank you

**Comment by aerkalov** [comment]
Thanks. Will take a look at this.

**Comment by kne1p** [comment]
this is related to pull request #86

**Comment by aerkalov** [comment]
Issue #99 should fix it all.
