### ISSUE TITLE
Can't display cover on first page

### ISSUE THREAD

**Issue by yomguy** [aerkalov/ebooklib#87]
Hi,
First, thank you for this great lib.
I don't manage to display the cover on first page. Is there any solution / option for that ? Do I need to add a page manually?
Thanks
G

**Comment by aerkalov** [comment]
Hi!

You should be able just to use "set_cover" method to define it, as you can see it here - https://github.com/aerkalov/ebooklib/blob/master/samples/02_cover_create/create.py

If it does not work you can paste sample of your code so we can figure out what is going on.

Aco

**Comment by yomguy** [comment]
Thanks for replying.
Yes I have used ser_cover method, but although the cover is well shown in the shelf of various readers, the cover is not on the first page of the book or (weird thing) on the last page with Calibre.

Here is my code:
https://github.com/Parisson/Telemeta/blob/dev/telemeta/views/epub.py#L43

The cover is added there:
https://github.com/Parisson/Telemeta/blob/dev/telemeta/views/epub.py#L103

and insert here:
https://github.com/Parisson/Telemeta/blob/dev/telemeta/views/epub.py#L187

G

**Comment by aerkalov** [comment]
Hi!

I would say you should add your cover page to the book "spine" (or even guide, depends what you want). 

Aco

**Comment by yomguy** [comment]
So adding it with its uid to the chapters and the chapters to the spine wouldn't be sufficient?
```
self.chapters.insert(0, 'cover')
self.book.spine = self.chapters
```
G

**Comment by aerkalov** [comment]
Defining just ID should work. Here is code sample how I do it in my project (with spine and guide):

```
    item = ebooklib.epub.EpubHtml(
        uid       = COVER_UID,
        title     = 'title',
        file_name = "{}/{}".format(DOCUMENTS_DIR, COVER_FILE_NAME),
        content   = COVER_XML % { "book_title" : epub_book.title })

    epub_book.add_item(item)
    epub_book.spine.insert(0, item)

    epub_book.guide.insert(0, {
        "type"  : "cover",
        "href"  : item.file_name,
        "title" : item.title,
    })
```

**Comment by yomguy** [comment]
Thank you, that works, but then the cover is in the TOC. Is there any options to avoid this?

**Comment by aerkalov** [comment]
It is not really in the TOC. epub_book.toc defines TOC (TOC in EPUB and created navigation page), while spine defines linear reading order. Depends of the ebook reader but yes, it ends up "as TOC" in the reader. Not really sure how to avoid it and this is the method some of the publishers (they publish at Amazon and Apple) who are using ebooklib are doing.

**Comment by yomguy** [comment]
Understood, thanks for the infos.
Well, having the cover in the toc is not really a pb in fact.
Cheers and congrats for this great module!
G
