### ISSUE TITLE
set.cover not working in Python 3.4

### ISSUE THREAD

**Issue by SamaneriVimala** [aerkalov/ebooklib#92]
In Python 2.7,  set.cover works fine like this:

    im = open('image.jpg').read()  
    book.set_cover(file_name=image.jpg',content=im,create_page=True)

But in Python 3.4 it fails with:
>UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte.

Apparently reading an image via the open method no longer works but I cannot find how to do it otherwise in Python3.

**Comment by SamaneriVimala** [comment]
The library seems to have some unicode problems.
Here's a shim that monkey patches the library and makes the problem go away; at the start of the script, after importing the library, include this code:

    from ebooklib import epub
    original_get_template = epub.EpubBook.get_template
    def new_get_template(*args, **kwargs):
        return original_get_template(*args, **kwargs).encode(encoding='utf8')
    epub.EpubBook.get_template = new_get_template

**Comment by aerkalov** [comment]
Thanks for this. The problem was that templates were defined as type 'str' and not 'bytes'. I fixed it where they are defined so monkey patching is not needed anymore.
