### ISSUE TITLE
tests/epub_parse.py doesn't transfer xhtml files?

### ISSUE THREAD

**Issue by Rojikku** [aerkalov/ebooklib#93]
Essentially, I want to make the filename = title for existing epubs.

https://pastebin.com/ZryRKCZc

I did that. Very successfully. Only to realize that, at some point, all the .xhtml files became 0 bytes. I have no idea why this is.
Considering I have a whole three lines of code that actually do anything, and none of them are wrong from what I can tell...I want to ask here.

What did I ____ up? Or, what went wrong? Is it even my fault?

**Comment by aerkalov** [comment]
Sorry for being too late with the response. Did you manage to fix this issue? Pastebin text has timedout and I can not see what did you try to do.

**Comment by Rojikku** [comment]
I can re upload it later, but no, I have not fixed it yet.

**Comment by aerkalov** [comment]
That would be great if you could do it!

**Comment by Rojikku** [comment]
I have two files it could be, so I uploaded them both. I believe I tried going about it another way, not sure I ever got anywhere.

https://pastebin.com/WnnWhbT4
